exp:
  num_epochs: 10

data:
  data_dir: "/content/drive/My Drive/split_dataset"
  batch_size: 2
  shuffle: True
  num_workers: 1

model:
  name: resnet18.a1_in1k
  num_classes: 6
  pretrained: True

criterion:
  name: cross_entropy

optimizer:
  name: adam
  lr: 0.0001
  weight_decay: 0.0001
  momentum: 0.9

lr_scheduler:
  step_size: 7
  gamma: 0.1
  